# travis-ci.org configuration


language: python


python:
    - 2.7
    - 3.2
    - 3.3
    - 3.4
    - pypy
    - pypy3


# travis-ci installs `mock` automatically
# also integrate with coveralls.io:

install:
    - pip install coveralls


script:
    - coverage run cnfg/test.py


after_success:
    coveralls
